### ISSUE TITLE
Suggestion: Don't print out to stdout if there is a default path it's going to save to

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/ts-force-gen#3]
Currently `ts-force-gen -j ts-force.config.json` is going to put the results in `./src/generated/sobs.ts`, but the command also prints the output to stdout. 

Seems a little unusual to have stuff getting output to two locations. Seems a little more reasonable to have just one ouput, and default to `./src/generated/sobs.ts`. If someone wanted to go somewhere else they could do something like `ts-force-gen -o /dev/stdout | sed 's/name\?/nameCustom/' > output.ts`

**Comment by ChuckJonas** [comment]
done in 2.0
